name: flutter_app_shortcut
description: A plugin for you to easily implement dynamic native app shortcut for Android and quick actions for IOS
version: 0.1.0
documentation: https://github.com/ngthailam/flutter_app_short_cut/blob/main/README.md
repository: https://github.com/ngthailam/flutter_app_short_cut
issue_tracker: https://github.com/ngthailam/flutter_app_short_cut/issues
platforms:
  android:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: vn.thailam.flutter_app_shortcut
        pluginClass: FlutterAppShortcutPlugin
      ios:
        pluginClass: SwiftFlutterAppShortcutPlugin
